#
# eons-world.eu
#

<VirtualHost *:80>
    DocumentRoot "C:/Servers/WebServers/eons-world.eu"

    ServerName eons-world.eu
    ServerAlias www.eons-world.eu

    <Directory "C:/Servers/WebServers/eons-world.eu">
      Options FollowSymLinks Indexes ExecCGI
      AllowOverride All
      allow from all
      Order allow,deny
      Require all granted
  	</Directory>
</VirtualHost>

<VirtualHost *:443>
    DocumentRoot "C:/Servers/WebServers/eons-world.eu"

    ServerName eons-world.eu
    ServerAlias www.eons-world.eu
	SSLEngine on
	SSLCertificateFile "conf/ssl.crt/server.crt"
	SSLCertificateKeyFile "conf/ssl.key/server.key"
    <Directory "C:/Servers/WebServers/eons-world.eu">
      Options FollowSymLinks Indexes ExecCGI
      AllowOverride All
      allow from all
      Order allow,deny
      Require all granted
  	</Directory>
</VirtualHost>

Alias /eons_client/ "C:/Servers/Client/Eons/"
<Directory "C:/Servers/Client/Eons/">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
    Header set Access-Control-Allow-Origin "*"
</Directory>

Alias /eons_client/ "C:/Servers/Client/Eons/"
<Directory "C:/Servers/Client/Eons/">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>
